### ISSUE TITLE
Supplemental files from /Users/kbehrman/Downloads

### ISSUE THREAD

**Issue by underdogadmin** [paiml/python_devops_book#16]
Greetings, 
Is there a source or repo with the various files referenced from /Users/kbehrman/Downloads?  For example, in Chapter 2 there are various xml, yaml, and csv files that are used but without the full version shown in the book.

**Comment by 1ckov** [comment]
I have the same issue with chapter 2, and cannot find any of the resources, so is this closed because the resources are there, or was it mistakenly closed?
