### ISSUE TITLE
Chapter 10. Infrastructure as Code - Cloudfront InvalidViewerCertificate error

### ISSUE THREAD

**Issue by jasonwhitedev** [paiml/python_devops_book#17]
Deployment fails with this message: 
```error creating CloudFront Distribution: InvalidViewerCertificate: The specified SSL certificate doesn't exist, isn't in us-east-1 region, isn't valid, or doesn't include a valid certificate chain```

**Comment by griggheo** [comment]
Hi Jason - can you share the code you are using?

**Comment by jasonwhitedev** [comment]
Hi Grig, in the end I simply cloned this repo, so the code will be here: https://github.com/paiml/python_devops_book/tree/master/src/chap10-InfraAsCode/terraform

If this is working for you, then I must be doing something wrong, maybe with the domain name setup in AWS console.

**Comment by griggheo** [comment]
OK - then please make sure you create your ACM certificate in us-east-1.

**Comment by jasonwhitedev** [comment]
Just checked again and everything is set to us-east-1. Please can you confirm that this is working for you.

**Comment by griggheo** [comment]
If you want to fork the repo and add your code, or include your code in one
of your own repos, let me know and I can take a look at it.

**Comment by jasonwhitedev** [comment]
There's no need. I simply cloned this repo. I've only changed the domain name.

**Comment by griggheo** [comment]
Ok, I'll give it another try. What version of terraform and/or pulumi
are you using?

**Comment by jasonwhitedev** [comment]
Thank you. I am using Terraform v0.12.26. I am not attempting this using Pulumi.

**Comment by griggheo** [comment]
Hi Jason,

I just went through the instructions in Chapter 10 in the book using Terraform v0.12.26 and it worked fine. I had to follow the "Manual provisoning" section in creating a DNS Route53 zone in AWS which I called grig.dev, and then pointing one my grig.dev domain in namecheap to the name servers listed in the NS record for grig.dev in AWS. 

I had these entries in variables.tf:

variable "aws_region" {
  default = "us-east-1"
}

variable "domain_name" {
  default = "grig.dev"
}

Then I went through 

terraform init
terraform plan
terraform apply

and I had to fix the syntax for referring to variables in TF 0.12 vs TF 0.11. Things like:

 provider "aws" {
-  region = "${var.aws_region}"
+  region = var.aws_region
 }

Other than that, I was able to create the S3 bucket, the SSL cert and the Cloudfront distro.

Let me know if you've been following these steps...maybe you skipped some?

**Comment by jasonwhitedev** [comment]
Great news Grig, this is working for me now. Thank you for your help.
The main cause of my issue was that I missed this manual step, as explained in the book:

_"Use the AWS console to add the necessary Route 53 records for the validation process. The certificate is normally validated and issued in a few minutes."_.

Sorry for me not being able to follow instructions :/

Thanks again for putting up with me.

**Comment by griggheo** [comment]
Glad it worked for you, Jason, and no worries, please open issues whenever
you hit a bump.
